apiVersion: v1
kind: ReplicationController
metadata:
  name: api-musicstore
  namespace: musicstore
  labels:
    name: api-musicstore
spec:
  replicas: 1
  selector:
    name: api-musicstore
  template:
    metadata:
      labels:
        name: api-musicstore
    spec:
      containers:
        - name: api-musicstore
          image: api-musicstore:v1
          ports:
            - name: backend-port
              containerPort: 9000
